spring.application.name=blockchaincamera

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.websocket.allow-origin-patterns=*

logging.level.com.example.blockchaincamera=DEBUG


spring.devtools.restart.enabled=false

app.difficulty=3

app.mining.intervalSeconds=10

app.node.connectToWorkers=false


app.image.similarity.mode=max
app.image.similarity.dhashWeight=1.0
app.image.similarity.ssimWeight=0.0
app.image.similarity.perfectDhash=0.98